apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-backend
  template:
    metadata:
      labels:
        app: monitor-backend
    spec:
      containers:
        - name: monitor-backend
          image: ops86199/dashboard-backend:latest
            ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: dockerhub-cred   # only if image is private
