apiVersion: v1
kind: Service
metadata:
  name: monitor-frontend-svc
spec:
  selector:
    app: monitor-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # external access port
      targetPort: 3000