apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-frontend
  template:
    metadata:
      labels:
        app: monitor-frontend
    spec:
      containers:
        - name: monitor-frontend
          image: <your-dockerhub-username>/dashboard-frontend:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhub-cred   # only if image is private
